SELECT BOOK.CATEGORY, SUM(sales) AS TOTAL_SALES
FROM (
SELECT BOOK_ID a, SUM(SALES) sales FROM BOOK_SALES 
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY BOOK_ID
) TBLE JOIN BOOK ON BOOK.BOOK_ID = a 
GROUP BY CATEGORY
ORDER BY CATEGORY ASC